# Generated by Django 4.1.2 on 2022-12-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=200)),
                ('userId', models.CharField(max_length=200)),
                ('productId', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('totalprice', models.CharField(max_length=200)),
            ],
        ),
    ]
