# Generated by Django 4.1.2 on 2023-01-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userId', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userContact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('orderAmount', models.CharField(max_length=50)),
                ('paymentMethod', models.CharField(default=None, max_length=50)),
                ('transactionId', models.TextField(default=None)),
            ],
        ),
    ]
